Working on first fully working workflow.

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -1,6 +1,7 @@
 env:
     SQLITE_PAGE: https://sqlite.org
     OUTPUT_FILES: sqlite3.c sqlite3.h sqlite3ext.h shell.c
+    WORKFLOWS: build_linux_x64.yml build_windows_x64.yml
  
 name: Generate Amalgamation
 
@@ -76,24 +77,79 @@ jobs:
             - name: Trigger binary build workflows
               shell: bash
               run: |
+                created_dt=$(date +%Y-%m-%dT%H:%M:%S)
                 payload="{\"inputs\":{\"INT_VER\":\"${{ env.INT_VER }}\",\"PARENT_RUN_ID\":\"${{ github.run_id }}\"},\"ref\":\"main\"}"
-                echo $payload
-                #for wid in "build_linux_x64.yml"
-                #do
-                    wid=build_linux_x64.yml
+                
+                
+                for wname in ${{ env.WORKFLOWS }}
+                do
                     curl -L \
                       -X POST \
                       -H "Accept: application/vnd.github+json" \
                       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       -H "X-GitHub-Api-Version: 2022-11-28" \
-                      https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/workflows/$wid/dispatches \
+                      https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/workflows/$wname/dispatches \
                       -d $payload
-                    wid=build_windows_x64.yml
-                    curl -L \
-                      -X POST \
-                      -H "Accept: application/vnd.github+json" \
-                      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                      -H "X-GitHub-Api-Version: 2022-11-28" \
-                      https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/workflows/$wid/dispatches \
-                      -d $payload
-                #done
+                done
+
+            - name: Wait a bit for workflows creation
+              shell: bash
+              run: sleep 5
+                
+            - name: Wait for workflows to complete
+              shell: bash
+              run: |
+                wid_list=()
+                for wname in ${{ env.WORKFLOWS }}
+                do
+                    wid_list+=( $(
+                            curl -L \
+                              -H "Accept: application/vnd.github+json" \
+                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                              -H "X-GitHub-Api-Version: 2022-11-28" \
+                              https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/workflows/$wname/runs?created=\>$created_dt | jq '.workflow_runs[0].id' \
+                              -d $payload
+                        ) )
+                done
+                
+                echo "Workflow IDs to wait for: ${wid_list[@]}"
+                for wid in ${wid_list[@]}
+                do
+                    echo "Waiting for ID: $wid"
+                    it=1
+                    status=""
+                    while [ "$status" != "completed" ]
+                    do
+                        echo "Iteration $it..."
+                        it=$((it + 1))
+
+                        resp=$(
+                                curl -L \
+                                  -H "Accept: application/vnd.github+json" \
+                                  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                                  -H "X-GitHub-Api-Version: 2022-11-28" \
+                                  https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/workflows/$wname/runs/$wid
+                            )
+                        status=$(echo $resp | jq '.status')
+                        result=$(echo $resp | jq '.conclusion')
+                        if [ "$status" == "completed" && "$result" != "success" ]
+                        then
+                            echo "Child build has failed: https://github.com/pawelsalawa/sqlite3-sqls/actions/runs/$wid"
+                            exit 1
+                        fi
+
+                        if [ "$status" != "completed" ]
+                        then
+                            sleep 30
+                        fi
+                    done
+                    echo "Child build $wid finished successfully."
+                done
+                
+                echo "All child workflows finished successfully."
+                echo "CHILD_IDS=\"${wid_list[@]}\"" >> $GITHUB_ENV
+
+            - name: Create release
+              shell: bash
+              run: |
+                echo "test: ${{ env.CHILD_IDS }}"
